name: bullseye_lang
description: A pure functional language that compiles to Dart.
version: 0.1.0
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/bullseye
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  analyzer:
  args: ^2.0.0
  cli_repl: ^0.2.0
  glob: ^2.0.0
  io: ^1.0.0
  path: ^1.0.0
  source_span: ^1.0.0
  string_scanner: ^1.0.0
  symbol_table: ^2.0.0
  vm_service: ^7.0.0
dev_dependencies:
  lints: ^1.0.0
executables:
  blsc: blsc
  bullseye: bullseye
